import { defineConfig } from '@playwright/test';
import * as path from 'path';
import { APP_URLS } from './src/constants';

export default defineConfig({
  testDir: './tests',

  // Using project dependencies for setup (see projects block below)

  /* Set increased timeouts */
  timeout: 120000,
  expect: { timeout: 15000 },

  /* Guarantee tests run one after the other */
  fullyParallel: false,
  workers: 1,

  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: 'html',

  use: {
    baseURL: APP_URLS.HOME_URL,
    trace: 'on-first-retry',
    viewport: null,
    launchOptions: {
      args: ['--start-maximized'],
      slowMo: 1000,
    },
    /* Tell all tests to use the session state generated by globalSetup */
    storageState: path.join(__dirname, 'playwright/.auth/user.json'),
  },

  /* Configure setup and main test projects */
  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
    },
    {
      name: 'chromium',
      use: { browserName: 'chromium' },
      dependencies: ['setup'],
    },
  ],
});